<a href="https://colab.research.google.com/github/KristannaPerez/KristannaPerez/blob/main/LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

La factorizacion LU descompone una matriz cuadrada A en el producto de una matriz triangular inferior L y una matriz triangular superior U \\n
$A=L•U$

Calculamos la matriz L osea triangular inferior con $l_{ii}=1$ (diagonal de unos). \\n
Calculamos la matriz U osea triangular superior.

Primero resolvemos $Ly=b$ mediante sustitucion hacia adelante, luego resolvemos $Ux=y$ mediante sustitucion hacia atras y asi obtenemos los resultados.

In [3]:
import numpy as np

def factorizacion_lu(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        # Calcular elementos de U
        for j in range(i, n):
            U[i, j] = A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))

        # Calcular elementos de L
        for j in range(i, n):
            if U[i, i] == 0:
                raise ValueError("Factorización imposible: pivote nulo.")
            L[j, i] = (A[j, i] - sum(L[j, k] * U[k, i] for k in range(i))) / U[i, i]

    return L, U

def sustitucion_adelante(L, b):
    n = len(L)
    y = np.zeros(n)
    for i in range(n):
        y[i] = (b[i] - sum(L[i, j] * y[j] for j in range(i))) / L[i, i]
    return y

def sustitucion_atras(U, y):
    n = len(U)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - sum(U[i, j] * x[j] for j in range(i + 1, n))) / U[i, i]
    return x

def resolver_sistema(A, b):
    L, U = factorizacion_lu(A)
    y = sustitucion_adelante(L, b)
    x = sustitucion_atras(U, y)
    return L, U, x

# Ejemplo 2
A = np.array([
    [1, 1, 0, 3],
    [2, 1, -1, 1],
    [3, -1, -1, 2],
    [-1, 2, 3, -1]
], dtype=float)

b = np.array([8, 7, 14, -7], dtype=float)

# Resolver el sistema
L, U, x = resolver_sistema(A, b)

# Mostrar resultados
print("Matriz L:")
print(L)
print("\nMatriz U:")
print(U)
print("\nSolución del sistema (x):")
print(x)


Matriz L:
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

Matriz U:
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]

Solución del sistema (x):
[ 3. -1.  0.  2.]
